# Generated by Django 5.0 on 2023-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
